### ISSUE TITLE
some issue loading fits images

### ISSUE THREAD

**Issue by helmarw** [farhi/astrotnstack#1]
>> astrotnstack('StackInput/*.fits','aitxrq_2023-12-17T21-43-29.698_DARKFRAMEMEAN.fits','');
astrotnstack: E. Farhi (2017) GPL2
astrotnstack: subtracting dark frame /Users/helmar/Downloads/aitxrq/aitxrq_2023-12-09T16-50-54.180_EnhancedVision/aitxrq_2023-12-17T21-43-29.698_DARKFRAMEMEAN.fits for all images.
Warning: The ability to read FITS files with IMREAD may be removed in a future release. Use FITSREAD to import FITS files. 
> In readfits (line 11)
In imread/call_format_specific_reader (line 449)
In imread (line 440)
In astrotnstack (line 151) 
Error using imread (line 440)
CFITSIO library error (412): datatype conversion overflow

Error in astrotnstack (line 151)
  dark = imread(dark{1});

(Matlab 2023b and also Matlab202b, MacOS)

Best
Helmar

**Comment by farhi** [comment]
Hi Helmar,

The Astrostack project is obsolete, and has been replaced by Mastrostack at:

- https://gitlab.com/astrophotography/matlab-mastrostack

I think it better handles FITS images...

**Comment by helmarw** [comment]
ok, thought so, but sadly mastrostack has other problem, well, maybe someone answers there
